on:
  push:
    # branches:
    #   - main
    # paths:
    #   - src/**
    #   - package.json
    #   - .github/**
    tags:
      - "*"

jobs:
  build:
    name: build static app
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      PUBLIC_API_HOST: "https://delegationz.fly.dev"
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Build SPA
        run: pnpm build:fly
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: dist
          path: build/*

  release:
    name: create tagged release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs: [build]
    permissions:
      contents: write
      packages: write
    steps:
      - name: Download artifact result from build step
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist
      - name: Display structure of downloaded files dist
        run: ls -R
      - name: Zip everything
        run: zip -r "dlgz_app_spa_${{ github.ref_name }}.zip" dist
      - name: Release app
        uses: softprops/action-gh-release@v1
        with:
          files: |
            *.zip
